[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npx pnpm@10.0.0 install --no-frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm@10.0.0 build"]

[start]
cmd = "npx pnpm@10.0.0 db:migrate && npx pnpm@10.0.0 start"
